# SPDX-License-Identifier: MPL-2.0
name = "SiliconCore"
uuid = "01a11d29-d88c-832a-9ded-976af4b7dc75"
authors = ["Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>"]
version = "0.1.1"
license = "MPL-2.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
